substitutions:
  name: "ha-remote"
  friendly_name: "HA Remote Controller"

esphome:
  name: harem
  friendly_name: HARem

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "7knRB3/EL4Fq8Foul7Yhv+pcABzyLXHSQxa9bTzzQqg="

ota:
  - platform: esphome
    password: "ad2825446c99da7cb65d49d3f691d24e"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

    - ssid: !secret 2_wifi_ssid
      password: !secret 2_wifi_password

    - ssid: !secret 3_wifi_ssid
      password: !secret 3_wifi_password
    # Set a low power save mode to speed up the connection when waking up
  power_save_mode: LIGHT
  
  # Callback when Wi-Fi disconnects
  on_disconnect:
    - logger.log: "Wi-Fi disconnected!"
    - delay: 180s   # wait 3 minutes
    - if:
        condition:
          wifi.connected:
        then:
          - logger.log: "Wi-Fi reconnected within 3 minutes."
        else:
          - logger.log: "Wi-Fi still down, rebooting..."



  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Harem Fallback Hotspot"
    password: "S6OlfI3QTLQU"

captive_portal:

# I2C Configuration for OLED
i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
  id: bus_a

# Font configuration
font:
  - file: "gfonts://Roboto"
    id: font_main
    size: 14
  - file: "gfonts://Material Icons"
    id: font_icon
    size: 24
    glyphs:
      - "\U0000E0F0" # lightbulb (was mdi-lightbulb-on)
      - "\U0000E8AC" # power_settings_new (was mdi-power-plug? using generic power for now)
      - "\U0000E335" # power_off (was mdi-lightbulb-off? using close/off)
      - "\U0000E02C" # movie
      - "\U0000E63C" # power (plug)
  - file: "gfonts://Roboto"
    id: font_header
    size: 12
  - file: "gfonts://Roboto"
    id: font_small
    size: 10

# Globals to track state
# Globals removed - Logic moved to Home Assistant

# Import Home Assistant Entities
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true
    name: "Encoder Button"
    id: encoder_button
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - logger.log:
              format: "Short Click Detected!"
              level: INFO
          - homeassistant.event:
              event: esphome.remote_action
              data:
                action: click
      - min_length: 600ms
        max_length: 10s
        then:
          - logger.log:
              format: "Long Click Detected!"
              level: INFO
          - homeassistant.event:
              event: esphome.remote_action
              data:
                action: back

  # Status sensors removed - Managed by Home Assistant text
    
text_sensor:
  - platform: homeassistant
    id: remote_line_1
    entity_id: input_text.harem_line_1
  - platform: homeassistant
    id: remote_line_2
    entity_id: input_text.harem_line_2
  - platform: homeassistant
    id: remote_line_3
    entity_id: input_text.harem_line_3
  - platform: homeassistant
    id: remote_line_4
    entity_id: input_text.harem_line_4
  - platform: homeassistant
    id: remote_line_5
    entity_id: input_text.harem_line_5

sensor:
  - platform: rotary_encoder
    id: encoder
    pin_a:
      number: GPIO8
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO9
      mode: INPUT_PULLUP
    resolution: 1
    on_value:
      then:
        - component.update: my_display
        - if:
            condition:
              lambda: 'return x > 0;'
            then:
              - homeassistant.event:
                  event: esphome.remote_action
                  data:
                    action: next
            else:
              - homeassistant.event:
                  event: esphome.remote_action
                  data:
                    action: prev
        - lambda: 'id(encoder).state = 0;' # Reset encoder to avoid overflow and keep relative logic

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    id: my_display
    i2c_id: bus_a
    update_interval: 0.1s
    lambda: |-
      // Draw Interface - 5 Lines
      
      // Line 1 (Index - 2) - y=6 (Safe from Top Bezel)
      if (id(remote_line_1).has_state()) {
        it.printf(64, 6, id(font_small), TextAlign::TOP_CENTER, "%s", id(remote_line_1).state.c_str());
      }
      
      // Line 2 (Index - 1) - y=17
      if (id(remote_line_2).has_state()) {
        it.printf(64, 17, id(font_small), TextAlign::TOP_CENTER, "%s", id(remote_line_2).state.c_str());
      }

      // Line 3 (Selected) - y=28 (Centered with Scroll)
      if (id(remote_line_3).has_state()) {
        std::string text = id(remote_line_3).state;
        int x1, y1, width, height;
        it.get_text_bounds(0, 0, text.c_str(), id(font_header), TextAlign::TOP_LEFT, &x1, &y1, &width, &height);
        
        if (width <= 128) {
          // Fits on screen - Center it
          it.printf(64, 28, id(font_header), TextAlign::TOP_CENTER, "%s", text.c_str());
        } else {
          // Too long - Scroll it
          // Speed factor: 40ms/pixel
          int x = 128 - (millis() / 40) % (width + 128);
          it.print(x, 28, id(font_header), TextAlign::TOP_LEFT, text.c_str());
        }
      } else {
        it.print(64, 28, id(font_header), TextAlign::TOP_CENTER, "Waiting...");
      }

      // Line 4 (Index + 1) - y=41
      if (id(remote_line_4).has_state()) {
        it.printf(64, 41, id(font_small), TextAlign::TOP_CENTER, "%s", id(remote_line_4).state.c_str());
      }

      // Line 5 (Index + 2) - y=52 (Safe from Bottom Bezel)
      if (id(remote_line_5).has_state()) {
        it.printf(64, 52, id(font_small), TextAlign::TOP_CENTER, "%s", id(remote_line_5).state.c_str());
      }



# Script removed - Logic moved to Home Assistant
