blueprint:
  name: "HARem: Universal ESPHome Remote Controller"
  description: "Handles navigation, device toggling, and multi-line display logic for the HARem remote."
  domain: automation
  input:
    menu_path:
      name: Menu Path Helper
      description: "input_text to store current location (ROOT or Area Name)"
      selector:
        entity:
          domain: input_text
    menu_index:
      name: Menu Index Helper
      description: "input_number to store scroll position"
      selector:
        entity:
          domain: input_number
    line_1:
      name: Line 1 Helper
      selector:
        entity:
          domain: input_text
    line_2:
      name: Line 2 Helper
      selector:
        entity:
          domain: input_text
    line_3:
      name: Line 3 Helper (Selected)
      selector:
        entity:
          domain: input_text
    line_3_status:
      name: Line 3 Status Helper
      selector:
        entity:
          domain: input_text
    line_4:
      name: Line 4 Helper
      selector:
        entity:
          domain: input_text
    line_5:
      name: Line 5 Helper
      selector:
        entity:
          domain: input_text
    overlay:
      name: Overlay Helper
      selector:
        entity:
          domain: input_text

mode: queued
max: 10

trigger:
  - platform: event
    event_type: esphome.remote_action

action:
  # 1. HANDLE ACTION
  - variables:
      action: "{{ trigger.event.data.action }}"
      path_entity: !input menu_path
      idx_entity: !input menu_index
      path: "{{ states(path_entity) }}" 
      idx: "{{ states(idx_entity) | int }}"
      
  - variables:
      list_size: >
        {% if path == 'ROOT' or path == '' %} {{ areas() | length }}
        {% else %} {{ area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | list | length }} {% endif %}

  - choose:
      # ROTATE -> Change Index
      - conditions: "{{ action == 'next' and list_size > 0 }}"
        sequence:
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: "{{ (idx + 1) % list_size }}"}
            
      - conditions: "{{ action == 'prev' and list_size > 0 }}"
        sequence:
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: "{{ (idx - 1) % list_size }}"}

      # CLICK -> Enter/Toggle
      - conditions: "{{ action == 'click' and list_size > 0 }}"
        sequence:
          - if: "{{ path == 'ROOT' or path == '' }}"
            then:
              - variables:
                  areas_list: "{{ areas() | sort }}"
                  selected_area: "{{ areas_list[idx % list_size] }}"
              - service: input_text.set_value
                target: {entity_id: !input menu_path}
                data: {value: "{{ selected_area }}"}
              - service: input_number.set_value
                target: {entity_id: !input menu_index}
                data: {value: 0}
            else:
              - variables:
                  entities: "{{ area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | sort }}"
                  selected_entity: "{{ entities[idx % list_size] }}"
                  friendly: "{{ state_attr(selected_entity, 'friendly_name') }}"
                  current_state: "{{ states(selected_entity) }}"
                  new_message: >
                     {% if current_state == 'on' %} Turning Off...
                     {% elif current_state == 'off' %} Turning On...
                     {% else %} Activating... {% endif %}
              
              # 1. Show Feedback Logic (Overlay)
              - service: input_text.set_value
                target: {entity_id: !input overlay}
                data: {value: "{{ new_message }}"}
                
              # 2. Perform Action
              - service: homeassistant.toggle
                target: {entity_id: "{{ selected_entity }}"}
              
              # 3. Wait for State Change (Timeout 10s)
              - wait_template: "{{ states(selected_entity) != current_state }}"
                timeout: "00:00:10"
                
              # 4. Handle Result
              - if: "{{ not wait.completed }}"
                then:
                  - service: input_text.set_value
                    target: {entity_id: !input overlay}
                    data: {value: "Failed!"}
                  - delay: "00:00:02"
                
              # 5. Clear Overlay
              - service: input_text.set_value
                target: {entity_id: !input overlay}
                data: {value: ""}

      # BACK -> Exit Room
      - conditions: "{{ action == 'back' and path != 'ROOT' }}"
        sequence:
          - variables:
              sorted_areas: "{{ areas() | sort }}"
              restore_idx: "{{ sorted_areas.index(path) if path in sorted_areas else 0 }}"
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: "{{ restore_idx }}"}
          - service: input_text.set_value
            target: {entity_id: !input menu_path}
            data: {value: "ROOT"}

  # 2. UPDATE DISPLAY
  - variables:
      path: "{{ states(path_entity) }}" 
      idx: "{{ states(idx_entity) | int }}"
  
  - if: "{{ path == 'ROOT' or path == '' }}"
    then:
      - variables:
          list: "{{ areas() | sort }}"
      - if: "{{ list | length > 0 }}"
        then:
          - service: input_text.set_value
            target: {entity_id: !input line_1}
            data: {value: "{{ area_name(list[(idx - 2) % list|length]) if list|length > 2 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_2}
            data: {value: "{{ area_name(list[(idx - 1) % list|length]) if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3}
            data: {value: "> {{ area_name(list[idx % list|length]) }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3_status}
            data: {value: ""}
          - service: input_text.set_value
            target: {entity_id: !input line_4}
            data: {value: "{{ area_name(list[(idx + 1) % list|length]) if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_5}
            data: {value: "{{ area_name(list[(idx + 2) % list|length]) if list|length > 2 else '' }}"}
        else:
           - service: input_text.set_value
             target: {entity_id: !input line_3}
             data: {value: "No Areas Found"}

    else:
      - variables:
          list: "{{ area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | sort }}"
      - if: "{{ list | length > 0 }}"
        then:
          - service: input_text.set_value
            target: {entity_id: !input line_1}
            data: {value: "{{ state_attr(list[(idx - 2) % list|length], 'friendly_name') if list|length > 2 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_2}
            data: {value: "{{ state_attr(list[(idx - 1) % list|length], 'friendly_name') if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3}
            data: {value: "> {{ state_attr(list[idx % list|length], 'friendly_name') }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3_status}
            data: {value: "({{ states(list[idx % list|length]) | truncate(12, True, '..') }})" }
          - service: input_text.set_value
            target: {entity_id: !input line_4}
            data: {value: "{{ state_attr(list[(idx + 1) % list|length], 'friendly_name') if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_5}
            data: {value: "{{ state_attr(list[(idx + 2) % list|length], 'friendly_name') if list|length > 2 else '' }}"}
        else:
           - service: input_text.set_value
             target: {entity_id: !input line_3}
             data: {value: "Empty Room"}
