blueprint:
  name: "HARem: Universal ESPHome Remote Controller"
  description: "Handles navigation, device toggling, and multi-line display logic for the HARem remote."
  domain: automation
  input:
    menu_path:
      name: Menu Path Helper
      description: "input_text to store current location (ROOT or Area Name)"
      selector:
        entity:
          domain: input_text
    menu_index:
      name: Menu Index Helper
      description: "input_number to store scroll position"
      selector:
        entity:
          domain: input_number
    line_1:
      name: Line 1 Helper
      selector:
        entity:
          domain: input_text
    line_2:
      name: Line 2 Helper
      selector:
        entity:
          domain: input_text
    line_3:
      name: Line 3 Helper (Selected)
      selector:
        entity:
          domain: input_text
    line_3_status:
      name: Line 3 Status Helper
      selector:
        entity:
          domain: input_text
    line_4:
      name: Line 4 Helper
      selector:
        entity:
          domain: input_text
    line_5:
      name: Line 5 Helper
      selector:
        entity:
          domain: input_text
    overlay:
      name: Overlay Helper
      selector:
        entity:
          domain: input_text
    guest_mode_switch:
      name: Guest Mode Switch
      description: "input_boolean to track Guest Mode"
      default: none
      selector:
        entity:
          domain: input_boolean
    guest_included_entities:
      name: "[Guest Mode] Allowed Entities"
      description: "Select ALL entities that should be visible in Guest Mode. The areas containing these entities will be automatically allowed."
      default: []
      selector:
        entity:
          multiple: true
  

mode: queued
max: 20

trigger:
  - platform: event
    event_type: esphome.remote_action

action:
  # 1. HANDLE ACTION
  - variables:
      action: "{{ trigger.event.data.action }}"
      path_entity: !input menu_path
      idx_entity: !input menu_index
      path: "{{ states(path_entity) }}" 
      idx: "{{ states(idx_entity) | int }}"
      guest_switch_entity: !input guest_mode_switch
      guest_ents_raw: !input guest_included_entities
      
  - variables:
      guest_ents: >
        {% if guest_ents_raw is string %}
          {{ [guest_ents_raw] }}
        {% else %}
          {{ guest_ents_raw }}
        {% endif %}
      list_size: >
        {% set gm = guest_switch_entity %}
        {% set is_guest = is_state(gm, 'on') if gm != 'none' else false %}
        {% if path == 'ROOT' or path == '' %}
          {% if is_guest %}
             {% set ns = namespace(areas=[]) %}
             {% for ent in guest_ents %}
               {% set a = area_id(ent) %}
               {% if a != none and a not in ns.areas %}
                 {% set ns.areas = ns.areas + [a] %}
               {% endif %}
             {% endfor %}
             {{ ns.areas | length }}
          {% else %}
             {{ areas() | length }}
          {% endif %}
        {% else %}
          {% set entities = area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | list %}
          {% if is_guest %}
            {{ entities | select('in', guest_ents) | list | length }}
          {% else %}
            {{ entities | length }}
          {% endif %}
        {% endif %}

  - choose:
      # ROTATE -> Change Index
      - conditions: "{{ action == 'next' and list_size > 0 }}"
        sequence:
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: "{{ (idx + 1) % list_size }}"}
            
      - conditions: "{{ action == 'prev' and list_size > 0 }}"
        sequence:
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: "{{ (idx - 1) % list_size }}"}

      # NEW: Handle toggle_guest from remote settings
      - conditions: "{{ action == 'toggle_guest' }}"
        sequence:
          - service: input_boolean.toggle
            target: {entity_id: !input guest_mode_switch}
          # Force nav back to ROOT to avoid being stuck in a restricted room
          - service: input_text.set_value
            target: {entity_id: !input menu_path}
            data: {value: "ROOT"}
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: 0}
          - variables:
              new_state: "{{ 'ON' if is_state(guest_switch_entity, 'on') else 'OFF' }}"
          - service: input_text.set_value
            target: {entity_id: !input overlay}
            data: {value: "Guest Mode: {{ new_state }}"}
          - delay: "00:00:02"
          - service: input_text.set_value
            target: {entity_id: !input overlay}
            data: {value: ""}
          - service: input_text.set_value
            target: {entity_id: !input line_5}
            data: {value: ""}

      # NEW: Handle clear_overlay
      - conditions: "{{ action == 'clear_overlay' }}"
        sequence:
          - service: input_text.set_value
            target: {entity_id: !input overlay}
            data: {value: ""}
          - service: input_text.set_value
            target: {entity_id: !input line_5}
            data: {value: ""}

      # CLICK -> Enter/Toggle
      - conditions: "{{ action == 'click' and list_size > 0 }}"
        sequence:
          - if: "{{ path == 'ROOT' or path == '' }}"
            then:
              - variables:
                  gm: "{{ guest_switch_entity }}"
                  is_guest: "{{ is_state(gm, 'on') if gm != 'none' else false }}"
                  areas_list: >
                    {% if is_guest %}
                       {% set ns = namespace(areas=[]) %}
                       {% for ent in guest_ents %}
                         {% set a = area_id(ent) %}
                         {% if a != none and a not in ns.areas %}
                           {% set ns.areas = ns.areas + [a] %}
                         {% endif %}
                       {% endfor %}
                       {{ ns.areas | sort }}
                    {% else %}
                       {{ areas() | sort }}
                    {% endif %}
                  selected_area: "{{ areas_list[idx % list_size] }}"
              - service: input_text.set_value
                target: {entity_id: !input menu_path}
                data: {value: "{{ selected_area }}"}
              - service: input_number.set_value
                target: {entity_id: !input menu_index}
                data: {value: 0}
            else:
              - variables:
                  gm: "{{ guest_switch_entity }}"
                  is_guest: "{{ is_state(gm, 'on') if gm != 'none' else false }}"
                  entities: >
                    {% set base = area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | list %}
                    {% if is_guest %}
                      {{ base | select('in', guest_ents) | list | sort }}
                    {% else %}
                      {{ base | sort }}
                    {% endif %}
                  selected_entity: "{{ entities[idx % list_size] }}"
                  friendly: "{{ state_attr(selected_entity, 'friendly_name') }}"
                  current_state: "{{ states(selected_entity) }}"
                  new_message: >
                     {% if current_state == 'on' %} Turning Off...
                     {% elif current_state == 'off' %} Turning On...
                     {% else %} Activating... {% endif %}
              
              # 1. Show Feedback Logic (Overlay)
              - service: input_text.set_value
                target: {entity_id: !input overlay}
                data: {value: "{{ new_message }}"}
                
              # 2. Perform Action
              - service: homeassistant.toggle
                target: {entity_id: "{{ selected_entity }}"}
              
              # 3. Wait for State Change (Timeout 10s)
              - wait_template: "{{ states(selected_entity) != current_state }}"
                timeout: "00:00:10"
                
              # 4. Handle Result
              - if: "{{ not wait.completed }}"
                then:
                  - service: input_text.set_value
                    target: {entity_id: !input overlay}
                    data: {value: "Failed!"}
                  - delay: "00:00:02"
                
              # 5. Clear Overlay
              - service: input_text.set_value
                target: {entity_id: !input overlay}
                data: {value: ""}
              - service: input_text.set_value
                target: {entity_id: !input line_5}
                data: {value: ""}

      # ROTATE HOLD -> Brightness / Volume Control
      - conditions: "{{ (action == 'rotate_cw_hold' or action == 'rotate_ccw_hold') and path != 'ROOT' and path != '' }}"
        sequence:
          - variables:
              start_idx: "{{ states(idx_entity) | int }}"
              gm: "{{ guest_switch_entity }}"
              is_guest: "{{ is_state(gm, 'on') if gm != 'none' else false }}"
              entities: >
                {% set base = area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | list %}
                {% if is_guest %}
                  {{ base | select('in', guest_ents) | list | sort }}
                {% else %}
                  {{ base | sort }}
                {% endif %}
              selected_entity: "{{ entities[start_idx % list_size] }}"
              domain: "{{ selected_entity.split('.')[0] }}"
              step: "{{ 10 if action == 'rotate_cw_hold' else -10 }}"
              line_5_ent: !input line_5
              current_pct: >
                 {% set val = states(line_5_ent) %}
                 {% set stored = val | int(-1) %}
                 {% if stored >= 0 and val != '' and val != 'unknown' %}
                   {{ stored }}
                 {% elif domain == 'light' %}
                   {{ (state_attr(selected_entity, 'brightness') | int(0) / 2.55) | round(0) }}
                 {% elif domain == 'media_player' %}
                   {{ state_attr(selected_entity, 'volume_level') | float(0) * 100 }}
                 {% else %} 0 {% endif %}
              new_pct: >
                 {% set val = (current_pct | float) + (step | int) %}
                 {{ 100 if val > 100 else (0 if val < 0 else val) }}
              
          - choose:
              # LIGHTS
              - conditions: "{{ domain == 'light' }}"
                sequence:
                  - service: light.turn_on
                    target: { entity_id: "{{ selected_entity }}" }
                    data:
                      brightness_step_pct: "{{ step }}"
                      transition: 0.1
                  - service: input_text.set_value
                    target: { entity_id: !input overlay }
                    data:
                      value: >
                        {% if new_pct | int >= 100 %}MAX 100%{% elif new_pct | int <= 0 %}MIN 0%{% else %}Bright {{ new_pct | int }}%{% endif %}
                  - service: input_text.set_value
                    target: { entity_id: !input line_5 }
                    data:
                      value: "{{ new_pct | int }}"
              
              # MEDIA PLAYERS (Volume)
              - conditions: "{{ domain == 'media_player' }}"
                sequence:
                  - service: media_player.volume_set
                    target: { entity_id: "{{ selected_entity }}" }
                    data:
                      volume_level: "{{ (state_attr(selected_entity, 'volume_level') | float(0)) + (step / 100.0) }}"
                  - service: input_text.set_value
                    target: { entity_id: !input overlay }
                    data:
                      value: >
                        {% if new_pct | int >= 100 %}MAX 100%{% elif new_pct | int <= 0 %}MIN 0%{% else %}Vol {{ new_pct | int }}%{% endif %}
                  - service: input_text.set_value
                    target: { entity_id: !input line_5 }
                    data:
                      value: "{{ new_pct | int }}"

          - delay: 0.05

      # BACK -> Exit Room
      - conditions: "{{ action == 'back' and path != 'ROOT' }}"
        sequence:
          - variables:
              sorted_areas: "{{ areas() | sort }}"
              restore_idx: "{{ sorted_areas.index(path) if path in sorted_areas else 0 }}"
          - service: input_number.set_value
            target: {entity_id: !input menu_index}
            data: {value: "{{ restore_idx }}"}
          - service: input_text.set_value
            target: {entity_id: !input menu_path}
            data: {value: "ROOT"}

  # 2. UPDATE DISPLAY
  - variables:
      path: "{{ states(path_entity) }}" 
      idx: "{{ states(idx_entity) | int }}"
      guest_ents: !input guest_included_entities
  
  - if: "{{ path == 'ROOT' or path == '' }}"
    then:
      - variables:
          gm: "{{ guest_switch_entity }}"
          is_guest: "{{ is_state(gm, 'on') if gm != 'none' else false }}"
          list: >
            {% if is_guest %}
               {% set ns = namespace(areas=[]) %}
               {% for ent in guest_ents %}
                 {% set a = area_id(ent) %}
                 {% if a != none and a not in ns.areas %}
                   {% set ns.areas = ns.areas + [a] %}
                 {% endif %}
               {% endfor %}
               {{ ns.areas | sort }}
            {% else %}
               {{ areas() | sort }}
            {% endif %}
      - if: "{{ list | length > 0 }}"
        then:
          - service: input_text.set_value
            target: {entity_id: !input line_1}
            data: {value: "{{ area_name(list[(idx - 2) % list|length]) if list|length > 2 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_2}
            data: {value: "{{ area_name(list[(idx - 1) % list|length]) if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3}
            data: {value: "> {{ area_name(list[idx % list|length]) }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3_status}
            data: {value: ""}
          - service: input_text.set_value
            target: {entity_id: !input line_4}
            data: {value: "{{ area_name(list[(idx + 1) % list|length]) if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_5}
            data: {value: "{{ area_name(list[(idx + 2) % list|length]) if list|length > 2 else '' }}"}
        else:
           - service: input_text.set_value
             target: {entity_id: !input line_3}
             data: {value: "No Areas Found"}

    else:
      - variables:
          gm: "{{ guest_switch_entity }}"
          is_guest: "{{ is_state(gm, 'on') if gm != 'none' else false }}"
          list: >
            {% set base = area_entities(path) | select('match', '^(light|switch|input_boolean|scene|script|button|cover|fan|lock|media_player)[.]') | list %}
            {% if is_guest %}
              {{ base | select('in', guest_ents) | list | sort }}
            {% else %}
              {{ base | sort }}
            {% endif %}
      - if: "{{ list | length > 0 }}"
        then:
          - service: input_text.set_value
            target: {entity_id: !input line_1}
            data: {value: "{{ state_attr(list[(idx - 2) % list|length], 'friendly_name') if list|length > 2 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_2}
            data: {value: "{{ state_attr(list[(idx - 1) % list|length], 'friendly_name') if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3}
            data: {value: "> {{ state_attr(list[idx % list|length], 'friendly_name') }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_3_status}
            data:
              value: >
                {% set entity = list[idx % list|length] %}
                {% set dom = entity.split('.')[0] %}
                {% set ns = namespace(can_dim=false) %}
                {% if dom == 'light' %}
                  {# Check for brightness support bit 0x01 (1) #}
                  {% if (state_attr(entity, 'supported_features') | int(0) | bitwise_and(1)) > 0 %}
                    {% set ns.can_dim = true %}
                  {% endif %}
                  {# Check unique color modes #}
                  {% set modes = state_attr(entity, 'supported_color_modes') %}
                  {% if modes %}
                    {% for m in modes %}
                      {% if m != 'onoff' %}
                         {% set ns.can_dim = true %}
                      {% endif %}
                    {% endfor %}
                  {% endif %}
                {% elif dom == 'media_player' %}
                   {# Check for volume_set bit 0x04 (4) #}
                   {% if (state_attr(entity, 'supported_features') | int(0) | bitwise_and(4)) > 0 %}
                     {% set ns.can_dim = true %}
                   {% endif %}
                {% endif %}
                ({{ states(entity) | truncate(12, True, '..') }}){{ ' *' if ns.can_dim else '' }}
          - service: input_text.set_value
            target: {entity_id: !input line_4}
            data: {value: "{{ state_attr(list[(idx + 1) % list|length], 'friendly_name') if list|length > 1 else '' }}"}
          - service: input_text.set_value
            target: {entity_id: !input line_5}
            data: {value: "{{ state_attr(list[(idx + 2) % list|length], 'friendly_name') if list|length > 2 else '' }}"}
        else:
           - service: input_text.set_value
             target: {entity_id: !input line_3}
             data: {value: "Empty Room"}
